--  기본 유저(관리자)

INSERT INTO USER_INFO ( USER_INFO_SEQ, USER_ID, USER_NM, PASSWORD, NICKNAME, EMAIL, MOBILE, MEMBERSHIP_CD
                      , ROLE, LOGIN_CNT, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(USER_INFO_SEQ), 0) + 1 FROM USER_INFO X)
       , 'TEST_ADMIN@test.com', 'TEST_ADMIN', '$2a$10$uC.82/DRiuAd/e0difcZweE.lvycJ8sT5aNQ7R/tfXfbEIVtlfBsO'
       , 'TEST_ADMIN', 'TEST_ADMIN@test.com'
       , '019-0000-0000', '10', 'ROLE_ADMIN', 0, 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

--  기본 유저(사용자)

INSERT INTO USER_INFO ( USER_INFO_SEQ, USER_ID, USER_NM, PASSWORD, NICKNAME, EMAIL, MOBILE, MEMBERSHIP_CD
                      , ROLE, LOGIN_CNT, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(USER_INFO_SEQ), 0) + 1 FROM USER_INFO X)
       , 'TEST_USER@test.com', 'TEST_USER', '$2a$10$uC.82/DRiuAd/e0difcZweE.lvycJ8sT5aNQ7R/tfXfbEIVtlfBsO', 'TEST_USER'
       , 'TEST_USER@test.com'
       , '011-0000-0000', '10', 'ROLE_USER', 0, 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

-- 공통 코드

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '001', '10', '실전문제', 1
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '001', '20', '모의고사', 2
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '002', '10', '공법', 1
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '002', '20', '형사법', 2
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '002', '30', '민사법', 3
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '003', '10', '자유게시판', 1
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '004', '10', '회원게시판', 1
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '005', '10', '기본회원', 1
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '005', '20', '인증회원', 2
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '005', '30', '빌보드회원', 3
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO CMMN_DTL_CD ( CMMN_DTL_CD_SEQ, GRP_CD, GRP_DTL_CD, GRP_DTL_NM, SRT_NO
                        , USE_YN, REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(CMMN_DTL_CD_SEQ), 0) + 1 FROM CMMN_DTL_CD X)
       , '005', '99', '관리자', 4
       , 'Y', 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

--  기본 문제 / 공법

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 1, '2022년도 11회 공법 - 1번 문제입니다.', '5', '해설1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 2, '2022년도 11회 공법 - 2번 문제입니다.', '3', '해설2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 3, '2022년도 11회 공법 - 3번 문제입니다.', '2', '해설3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 4, '2022년도 11회 공법 - 4번 문제입니다.', '1', '해설4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 5, '2022년도 11회 공법 - 5번 문제입니다.', '1', '해설5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 6, '2022년도 11회 공법 - 6번 문제입니다.', '1', '해설6'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 7, '2022년도 11회 공법 - 7번 문제입니다.', '1', '해설7'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 8, '2022년도 11회 공법 - 8번 문제입니다.', '4', '해설8'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 9, '2022년도 11회 공법 - 9번 문제입니다.', '3', '해설9'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '10', 10, '2022년도 11회 공법 - 10번 문제입니다.', '1', '해설10'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

-- 기본문제 / 형사법

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '20', 1, '2022년도 11회 형사법 - 1번 문제입니다.', '4', '해설6'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '20', 2, '2022년도 11회 형사법 - 2번 문제입니다.', '4', '해설7'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '20', 3, '2022년도 11회 형사법 - 3번 문제입니다.', '2', '해설8'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '20', 4, '2022년도 11회 형사법 - 4번 문제입니다.', '1', '해설9'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '20', 5, '2022년도 11회 형사법 - 5번 문제입니다.', '2', '해설10'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

-- 기본문제 / 민사법

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '30', 1, '2022년도 11회 민사법 - 1번 문제입니다.', '1', '해설11'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '30', 2, '2022년도 11회 민사법 - 2번 문제입니다.', '3', '해설12'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '30', 3, '2022년도 11회 민사법 - 3번 문제입니다.', '3', '해설13'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '30', 4, '2022년도 11회 민사법 - 4번 문제입니다.', '1', '해설14'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_MSTR_INFO ( QUIZ_MSTR_INFO_SEQ, EXAM_GRP_CD, EXAM_YEAR, EXAM_NO, SUBJECT_TYPE_CD, SRT_NO, CONTENT
                           , ANSWER, CMNTR
                           , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_MSTR_INFO_SEQ), 0) + 1 FROM QUIZ_MSTR_INFO X)
       , '10', '2022', 11, '30', 5, '2022년도 11회 민사법 - 5번 문제입니다.', '5', '해설15'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

-- 기본 문제 보기 / 공법

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 1, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 1, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 1, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 1, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 1, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 2, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 2, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 2, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 2, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 2, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 3, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 3, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 3, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 3, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 3, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 4, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 4, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 4, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 4, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 4, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 5, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 5, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 5, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 5, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 5, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 6, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 6, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 6, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 6, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 6, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 7, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 7, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 7, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 7, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 7, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 8, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 8, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 8, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 8, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 8, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 9, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 9, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 9, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 9, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 9, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 10, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 10, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 10, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 10, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 10, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

-- 기본 문제 보기 / 형사법

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 11, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 11, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 11, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 11, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 11, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 12, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 12, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 12, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 12, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 12, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 13, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 13, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 13, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 13, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 13, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 14, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 14, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 14, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 14, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 14, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 15, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 15, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 15, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 15, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 15, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

-- 기본 문제 보기 / 민사법

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 16, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 16, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 16, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 16, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 16, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 17, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 17, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 17, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 17, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 17, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 18, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 18, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 18, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 18, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 18, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 19, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 19, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 19, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 19, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 19, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 20, 1, 'example_1', '해설_1'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 20, 2, 'example_2', '해설_2'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 20, 3, 'example_3', '해설_3'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 20, 4, 'example_4', '해설_4'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;

INSERT INTO QUIZ_DTL_INFO ( QUIZ_DTL_INFO_SEQ, QUIZ_MSTR_INFO_SEQ, SRT_NO, CONTENT, CMNTR
                          , REGIST_ID, REGIST_NM, REG_TS, MDFY_TS, DEL_YN)
VALUES ( (SELECT IFNULL(MAX(QUIZ_DTL_INFO_SEQ), 0) + 1 FROM QUIZ_DTL_INFO X)
       , 20, 5, 'example_5', '해설_5'
       , 'SYETEM', 'SYETEM', NOW(), NOW(), 'N')
;