# prod

spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      location: /home/ec2-user/app/LawingMachine # 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB # 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 요청의 최대 사이즈 (default: 10MB)
  datasource:
    url: jdbc:mariadb://lawingmachine-db.cipovbn5uz6l.ap-northeast-2.rds.amazonaws.com:3306/lawingdb?autoReconnect=true
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 225634132446-k44mneq5c4ivqf9v2vhsij7skns3h9o5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: V_33F7A6ziMHh6lBxXTO
            client-secret: fMw1QBocH_
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://lawingmachine.com/login/oauth2/code/naver
          kakao:
            client-id: 61be32318f4b710d766a19da871ffb9e
            client-secret: a2a6ee78a07186fd65bea5bef4a8aa6c
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://lawingmachine.com/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.
