# 공통

spring:
  profiles:
    active: local
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.web.lawingMachine.app.**.vo
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 8090


logging:
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
#  logback:
#    rollingpolicy:
#      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
#  file:
#    name: logs
#    max-history: 7
#    max-size: 5KB
#    total-size-cap: 1MB
  level:
    root: INFO
    com.web.lawingmachine: DEBUG

---

# local

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3308/lawingdb?autoReconnect=true
    username: lawingdb
    password: lawingdb


---

# was

spring:
  config:
    activate:
      on-profile: was
  datasource:
    url: jdbc:mysql://rowingmachine.cakioqitx4ac.ap-northeast-2.rds.amazonaws.com:3306/rowing_db?autoReconnect=true
    username: root
    password: root1234
