# 공통

spring:
  main:
    allow-circular-references: true
  profiles:
    active: was
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.web.lawingMachine.app.**.vo
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 8080
  max-http-header-size: 400000

logging:
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
    logback:
      rollingpolicy:
        file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
  level:
    root: INFO
    com.web.lawingmachine: DEBUG
    org.springframework.security: DEBUG

---

# local

spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      #      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      #      file-size-threshold: 1MB #  파일이 메모리에 기록되는 임계값 (default: 0B)
      location: C:/Temp # 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB # 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 요청의 최대 사이즈 (default: 10MB)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/lawingdb?autoReconnect=true
    username: lawingdb
    password: lawingdb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 225634132446-k44mneq5c4ivqf9v2vhsij7skns3h9o5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          facebook:
            client-id: 1082362739246533
            client-secret: ed85f51536408416430531c10c9eaa8a
          naver:
            client-id: jRaeRzo8NPDxgwdHHNjX
            client-secret: q_k0N99pXC
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: 61be32318f4b710d766a19da871ffb9e
            client-secret: a2a6ee78a07186fd65bea5bef4a8aa6c
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.

---

# dev

spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      location: /home/ec2-user/app/LawingMachine # 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB # 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 요청의 최대 사이즈 (default: 10MB)
  datasource:
    url: jdbc:mariadb://lawingmachine-db.cakioqitx4ac.ap-northeast-2.rds.amazonaws.com:3306/lawingdb?autoReconnect=true
    username: root
    password: root1234
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: jRaeRzo8NPDxgwdHHNjX
            client-secret: q_k0N99pXC
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://3.34.72.206:8080/login/oauth2/code/naver
          kakao:
            client-id: a29beb7e4322a745cc6623d79102faee
            client-secret: b3cbca2f5e4008b44f5608c21a8de28e
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://3.34.72.206:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.

---

# was

spring:
  config:
    activate:
      on-profile: was
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 225634132446-k44mneq5c4ivqf9v2vhsij7skns3h9o5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: V_33F7A6ziMHh6lBxXTO
            client-secret: fMw1QBocH_
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://lawingmachine.com/login/oauth2/code/naver
          kakao:
            client-id: 61be32318f4b710d766a19da871ffb9e
            client-secret: a2a6ee78a07186fd65bea5bef4a8aa6c
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://lawingmachine.com/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.
  servlet:
    multipart:
      location: /home/ec2-user/app/LawingMachine # 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB # 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 요청의 최대 사이즈 (default: 10MB)
  datasource:
    url: jdbc:mariadb://lawingmachine-db.cipovbn5uz6l.ap-northeast-2.rds.amazonaws.com:3306/lawingdb?autoReconnect=true
    username: root
    password: root1234
