# 공통

spring:
  main:
    allow-circular-references: true
  profiles:
    active: local
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 225634132446-k44mneq5c4ivqf9v2vhsij7skns3h9o5.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 628464294973712
            client-secret: 75b9b5ba8d0a2a422384ecb8a7d553c9
custom:
  oauth2:
    kakao:
      client-id: a29beb7e4322a745cc6623d79102faee
      client-secret: b3cbca2f5e4008b44f5608c21a8de28e
    naver:
      client-id: jRaeRzo8NPDxgwdHHNjX
      client-secret: q_k0N99pXC

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.web.lawingMachine.app.**.vo
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 8090

jpa:
  database-platform: org.hibernate.dialect.MariaDB103Dialect
  properties:
    hibernate:
      format_sql: true
      hbm2ddl.auto: update
      implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  open-in-view: false
  show-sql: true

logging:
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  #  logback:
  #    rollingpolicy:
  #      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
  #  file:
  #    name: logs
  #    max-history: 7
  #    max-size: 5KB
  #    total-size-cap: 1MB
  level:
    root: INFO
    com.web.lawingmachine: DEBUG

---

# local

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/lawingdb?autoReconnect=true
    username: lawingdb
    password: lawingdb

---

# was

spring:
  config:
    activate:
      on-profile: was
  datasource:
    url: jdbc:mysql://rowingmachine.cakioqitx4ac.ap-northeast-2.rds.amazonaws.com:3306/rowing_db?autoReconnect=true
    username: root
    password: root1234
