# local

spring:
  config:
    activate:
      on-profile: local

  servlet:
    multipart:
      #      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      #      file-size-threshold: 1MB #  파일이 메모리에 기록되는 임계값 (default: 0B)
      #      location: C:/Temp # 업로드된 파일의 임시 저장 공간
      location: /Users/narafu/dev/attach # 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB # 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 요청의 최대 사이즈 (default: 10MB)

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lawingmachine_db?autoReconnect=true
    username: lawingmachine
    password: lawingmachine
#    url: jdbc:h2:tcp://localhost/~/lawingMachine
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    h2:
#      console:
#        enabled: true
#        path: /h2-console
#

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:db/data-mariadb.sql
      mode: always
      platform: mariadb

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 225634132446-k44mneq5c4ivqf9v2vhsij7skns3h9o5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          facebook:
            client-id: 1082362739246533
            client-secret: ed85f51536408416430531c10c9eaa8a
          naver:
            client-id: jRaeRzo8NPDxgwdHHNjX
            client-secret: q_k0N99pXC
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/login/oauth2/code/naver
          kakao:
            client-id: a29beb7e4322a745cc6623d79102faee
            client-secret: b3cbca2f5e4008b44f5608c21a8de28e
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.

#springdoc:
#  api-docs:
#    version: openapi_3_0
#    path: /local
#    groups:
#      enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true
#    groups-order: DESC
#    operationsSorter: method
#    disable-swagger-default-url: true
#  show-actuator: true
#  group-configs:
#    - group: stores
#      paths-to-match: /store/**
#    - group: users
#      packages-to-scan: org.springdoc.demo.app2