# dev

spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      location: /home/ec2-user/app/LawingMachine # 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB # 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 요청의 최대 사이즈 (default: 10MB)

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lawing-db.cakioqitx4ac.ap-northeast-2.rds.amazonaws.com:3306/lawingdb?autoReconnect=true
    username: admin
    password: root1234

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:db/data-mariadb.sql
      mode: never
      platform: mariadb

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: jRaeRzo8NPDxgwdHHNjX
            client-secret: q_k0N99pXC
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://13.124.83.80/login/oauth2/code/naver
          kakao:
            client-id: a29beb7e4322a745cc6623d79102faee
            client-secret: b3cbca2f5e4008b44f5608c21a8de28e
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://13.124.83.80/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.
