# 공통

spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.web.lawingMachine.app.**.vo
  configuration:
    mapUnderscoreToCamelCase: true

server:
  port: 8080
  max-http-request-header-size: 400000

management:
  endpoints:
    web:
      exposure:
        include: "health" # 외부로 노출할 엔드포인트를 지정합니다.
  endpoint:
    health:
      show-details: "always"

logging:
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
  level:
    root: INFO
    com.web.lawingmachine: DEBUG
    org.springframework.security: DEBUG
